### ISSUE TITLE
simple upload

### ISSUE THREAD

**Issue by OussamaElouarti** [kawkb/webserv#2]
request :
POST /upload HTTP/1.1
Host: e2r1p6.1337.ma:1337
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: close
Content-Disposition: form-data; name="uploadedfile"; filename="hello.txt"
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0
Content-Length: 23

asdadsadasdadsadasd

out of range exception

**Comment by moerradi** [comment]
fixed
